name: For dev environment

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      SHA: ${{ github.sha }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker build 
        run : docker build -t myimage:v1 .
        
      - name: Docker run
        run:  docker run -d -p 3000:8080 --name dev-${{ env.SHA }} myimage:v1
        
      - name: Push image on registry
        run : |
          docker login -u terezabisharyan -p ${{ secrets.HUB_PSW }}    
          docker push terezabisharyan/myimage:v1


